apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ksqldb.fullname" . }}
  labels:
  {{- include "ksqldb.labels" . | nindent 4 }}
data:
  {{- if .Values.secretPairs }}
  {{- range $key, $value := .Values.secretPairs }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
