{{- if .Values.secretPairs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ksqldb.fullname" . }}
  labels:
    {{- include "ksqldb.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secretPairs }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
  {{- end }}
{{- end }}
