apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksqldb.fullname" . }}
  labels:
    {{- include "ksqldb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ksqldb
      protocol: TCP
      name: http
  selector:
    {{- include "ksqldb.selectorLabels" . | nindent 4 }}
