{{- $fullName := include "licenseware-sdk-v2.workerAppResourceName" . -}}
{{- if not .Values.singleBinaryApp.enabled -}}
{{- if .Values.workerApp.enabled -}}
{{- if (and .Values.serviceMonitor.enabled .Values.alertingRule.enabled) -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "licenseware-sdk-v2.labels" . | nindent 4 }}
    {{- with .Values.workerApp.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ tpl (toYaml .) $ }}
  {{- end }}
spec:
    groups:
      - name: {{ printf "%s.rules" $fullName }}
        rules:
          - alert: {{ printf "%s_down" $fullName | camelcase }}
            expr: 100 * (count(up{job="{{ $fullName }}"} == 0) BY (job, namespace, service) / count(up{job="{{ $fullName }}"}) BY (job, namespace, service)) > 10
            for: {{ .Values.alertingRule.downFor }}
            labels:
              {{- range $key, $value := .Values.alertingRule.labels }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
            annotations:
                description: '{{`{{`}} printf "%.4g" $value {{`}}`}}% of the {{`{{`}} $labels.job {{`}}`}}/{{`{{`}} $labels.service {{`}}`}} targets in {{`{{`}} $labels.namespace {{`}}`}} namespace are down.'
                runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/targetdown/
                summary: One or more of the {{`{{`}} $labels.job {{`}}`}} targets are unreachable.
      {{- range $key, $value := .Values.alertingRule.additionalRules }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
