apiVersion: v2

name: kafka-connect-base
version: 0.1.0

appVersion: 7.2.2

description: Confluent Kafka connect base Helm Chart with the ability to add plugins as required
type: application
icon: https://github.com/licenseware/helm-charts/raw/gh-pages/static/png/kafka.jpg
