{{- if .Values.singleBinaryApp.enabled -}}
apiVersion: apps/v1
{{- if .Values.useStatefulSet }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "licenseware-sdk-v2.singleBinaryAppResourceName" . }}
  labels:
    {{- include "licenseware-sdk-v2.labels" . | nindent 4 }}
    {{- with .Values.singleBinaryApp.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  {{- if not (default .Values.global.autoscaling.enabled .Values.singleBinaryApp.autoscaling.enabled) }}
  {{- with (default .Values.global.replicaCount .Values.singleBinaryApp.replicaCount) }}
  replicas: {{ . }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "licenseware-sdk-v2.selectorLabels" . | nindent 6 }}
      {{- with .Values.singleBinaryApp.labels }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
  {{- if .Values.useStatefulSet }}
  serviceName: {{ include "licenseware-sdk-v2.singleBinaryAppResourceName" . }}
  {{- with .Values.podManagementPolicy }}
  podManagementPolicy: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with (default .Values.global.strategy .Values.singleBinaryApp.strategy) }}
  {{- if $.Values.useStatefulSet }}
  updateStrategy:
  {{- else }}
  strategy:
  {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with (default .Values.global.podAnnotations .Values.singleBinaryApp.podAnnotations) }}
      annotations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "licenseware-sdk-v2.selectorLabels" . | nindent 8 }}
        {{- with .Values.singleBinaryApp.labels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (or .Values.serviceAccount.create .Values.serviceAccount.name) }}
      serviceAccountName: {{ include "licenseware-sdk-v2.serviceAccountName" . }}
      {{- end }}
      {{- with (default .Values.global.terminationGracePeriodSeconds .Values.singleBinaryApp.terminationGracePeriodSeconds) }}
      terminationGracePeriodSeconds: {{ tpl (toYaml .) $ | int }}
      {{- end }}
      {{- with (default .Values.global.podSecurityContext .Values.singleBinaryApp.podSecurityContext) }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.singleBinaryApp.shareProcessNamespace }}
      shareProcessNamespace: {{ . }}
      {{- end }}
      initContainers:
      {{- with .Values.singleBinaryApp.initContainers }}
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.sourceCode.enabled }}
        - name: init-src
          {{- with (default .Values.global.securityContext .Values.singleBinaryApp.securityContext) }}
          securityContext:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - sh
            - -c
            - cp -r . /app
          {{- with (default .Values.global.resources .Values.singleBinaryApp.resources) }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: src
            mountPath: /app
      {{- end }}
      containers:
        - name: {{ tpl (default .Values.global.containerName .Values.singleBinaryApp.containerName) $ | default .Chart.Name }}
          {{- with .Values.singleBinaryApp.command }}
          command:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.singleBinaryApp.args }}
          args:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with (default .Values.global.securityContext .Values.singleBinaryApp.securityContext) }}
          securityContext:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraEnv }}
          env:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "licenseware-sdk-v2.fullname" . }}
          - secretRef:
              name: {{ include "licenseware-sdk-v2.fullname" . }}
          {{- with .Values.extraEnvFrom }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.singleBinaryApp.service.portName }}
              containerPort: {{ tpl .Values.singleBinaryApp.service.containerPort $ }}
              protocol: {{ .Values.singleBinaryApp.service.protocol }}
            {{- if .Values.serviceMonitorDramatiq.enabled }}
            - name: {{ tpl (toYaml .Values.serviceMonitorDramatiq.portName) $ }}
              containerPort: {{ tpl (toYaml .Values.serviceMonitorDramatiq.portNumber) $ | int }}
              protocol: TCP
            {{- end }}
          {{- with .Values.singleBinaryApp.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.singleBinaryApp.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with (default .Values.global.resources .Values.singleBinaryApp.resources) }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: upload-data
            mountPath: {{ .Values.configMapPairs.FILE_UPLOAD_PATH }}
          - name: tmp
            mountPath: /tmp
          {{- if .Values.persistence.sourceCode.enabled }}
          - name: src
            mountPath: {{ .Values.persistence.sourceCode.mountPath }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- tpl (toYaml .) $ | nindent 10 }}
          {{- end }}
        {{- with .Values.singleBinaryApp.sidecars }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      volumes:
      - name: upload-data
        {{- if and (not .Values.useStatefulSet) (or .Values.persistence.uploadFiles.enabled .Values.persistence.uploadFiles.create) }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.uploadFiles.claimName }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: tmp
        emptyDir: {}
      {{- if .Values.persistence.sourceCode.enabled }}
      - name: src
        persistentVolumeClaim:
          claimName: {{ tpl (include "licenseware-sdk-v2.sourceCodePvcName" $) $ }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with (default .Values.global.nodeSelector .Values.singleBinaryApp.nodeSelector) }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.affinity .Values.singleBinaryApp.affinity) }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.tolerations .Values.singleBinaryApp.tolerations) }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
  {{- if .Values.useStatefulSet }}
  {{- if .Values.persistence.uploadFiles.create }}
  volumeClaimTemplates:
  - metadata:
      name: upload-data
    spec:
      {{- with .Values.persistence.uploadFiles.accessModes }}
      accessModes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.uploadFiles.size }}
      {{- with .Values.persistence.uploadFiles.storageClassName }}
      storageClassName: {{ . }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}
