{{- if .Values.singleBinaryApp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "licenseware-sdk-v2.singleBinaryAppResourceName" . }}
  labels:
    {{- include "licenseware-sdk-v2.labels" . | nindent 4 }}
    {{- with .Values.singleBinaryApp.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.singleBinaryApp.service.type }}
  ports:
    - port: {{ .Values.singleBinaryApp.service.port }}
      targetPort: {{ .Values.singleBinaryApp.service.portName }}
      protocol: {{ .Values.singleBinaryApp.service.protocol }}
      name: {{ .Values.singleBinaryApp.service.portName }}
    {{- if .Values.serviceMonitorDramatiq.enabled }}
    - port: {{ .Values.serviceMonitorDramatiq.portNumber }}
      targetPort: {{ .Values.serviceMonitorDramatiq.portName }}
      protocol: TCP
      name: {{ .Values.serviceMonitorDramatiq.portName }}
    {{- end }}
  selector:
    {{- include "licenseware-sdk-v2.selectorLabels" . | nindent 4 }}
    {{- with .Values.singleBinaryApp.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
