apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ tpl .Values.service.targetPort $ }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  selector:
    {{- include "jupyter.selectorLabels" . | nindent 4 }}
