{{- if not .Values.useStatefulSet }}
{{- if .Values.persistence.uploadFiles.create -}}
{{- if .Values.persistence.uploadFiles.enabled -}}
{{- fail "You can only either create or pass claimName, not both!" }}
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl (.Values.persistence.uploadFiles.claimName) $ }}
  {{- with .Values.persistence.uploadFiles.annotations -}}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.uploadFiles.accessModes }}
  accessModes:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploadFiles.size }}
  {{- with .Values.persistence.uploadFiles.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
