{{- if not .Values.singleBinaryApp.enabled -}}
{{- if .Values.webApp.enabled -}}
{{- if (default .Values.global.autoscaling.enabled .Values.webApp.autoscaling.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "licenseware-sdk-v2.webAppResourceName" . }}
  labels:
    {{- include "licenseware-sdk-v2.labels" . | nindent 4 }}
    {{- with .Values.webApp.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "licenseware-sdk-v2.webAppResourceName" . }}
  {{- with (default .Values.global.autoscaling.minReplicas .Values.webApp.autoscaling.minReplicas) }}
  minReplicas: {{ tpl (toYaml .) $ }}
  {{- end }}
  maxReplicas: {{ default .Values.global.autoscaling.maxReplicas .Values.webApp.autoscaling.maxReplicas }}
  metrics:
    {{- with (default .Values.global.autoscaling.targetCPUUtilizationPercentage .Values.webApp.autoscaling.targetCPUUtilizationPercentage) }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ tpl (toYaml .) $ }}
    {{- end }}
    {{- with (default .Values.global.autoscaling.targetMemoryUtilizationPercentage .Values.webApp.autoscaling.targetMemoryUtilizationPercentage) }}
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: {{ tpl (toYaml .) $ }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
