apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mssql.fullname" . }}
data:
  ACCEPT_EULA: {{ .Values.config.acceptEula | quote }}
  MSSQL_PID: {{ .Values.config.edition }}
  MSSQL_DATA_DIR: {{ default "/var/opt/mssql" .Values.config.dataDir }}
  MSSQL_TCP_PORT: {{ default "1433" .Values.service.targetPort | quote }}
  MSSQL_COLLATION: {{ default "SQL_Latin1_General_CP1_CI_AS" .Values.config.collation }}
  MSSQL_LCID: {{ default "1033" .Values.config.lcid | quote }}
  MSSQL_ENABLE_HADR: {{ default "0" .Values.config.enableHadr | quote }}
