apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.fullname" . }}
data:
  SA_PASSWORD: {{ tpl (required "missing required value: .Values.config.saPassword" .Values.config.saPassword) $ | b64enc }}
