apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "licenseware-sdk-v2.fullname" . }}
  labels:
    {{- include "licenseware-sdk-v2.labels" . | nindent 4 }}
data:
  {{- with .Values.configMapPairs }}
  {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
