apiVersion: v1
kind: Secret
metadata:
  name: {{ include "licenseware-sdk-v2.fullname" . }}
  labels:
    {{- include "licenseware-sdk-v2.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secretPairs }}
  {{- if $value }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
  {{- end }}
  {{- end }}
